---
- name: install kibana
  yum:
    name: kibana
    state: present

- name: set kibana conf
  template:
    src: kibana_conf.yml
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: 0644
  notify: restart kibana

- name: Start Kibana
  service:
    name: kibana
    state: started
    enabled: yes
