---
- name: install initscripts
  yum:
    name: initscripts
    state: present

- name: Install Java 1.8
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Import Elasticsearch PGP key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: set Elasticsearch Yum repository
  template:
    src: elasticsearch_repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: 0644

- name: Install Elasticsearch
  include: elasticsearch.yml

- name: Install Logstash
  include: Logstash.yml

- name: Install Kibana
  include: kibana.yml
