---
- hosts: test_docker_container2
  connection: docker
  environment:
    http_proxy: "{{http_proxy}}"
    https_proxy: "{{http_proxy}}"
    no_proxy: "{{no_proxy}}"
  vars:
    http_proxy: http://jp-proxy.jp.oracle.com:80
    no_proxy: "localhost,127.0.0.1, 0.0.0.0"
  tasks:
    - name: install initscripts
      yum:
        name: initscripts
        state: present

    - name: Install Java 1.8
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Import Elasticsearch PGP key
      rpm_key:
        state: present
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: set Elasticsearch RPM repository
      template:
        src: el_rpm
        dest: /etc/yum.repos.d/elasticsearch.repo
        owner: root
        group: root
        mode: 0644

    - name: install Elasticsearch
      yum:
        name: elasticsearch
        state: present

    - name: set Elasticsearch config
      template:
        src: elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: root
        mode: 0644
      notify: restart elasticsearch

    - name: install Logstash
      yum:
        name: logstash
        state: present

    - name: delete logstash upstart script
      file:
        path: /etc/init/logstash.conf
        state: absent

    - name: set Logstash conf
      template:
        src: logstash_conf
        dest: /etc/logstash/conf.d/tomcat.conf
        owner: root
        group: root
        mode: 0644

    - name: create /opt/logstash dir
      file:
        path: /opt/logstash
        state: directory
        owner: root
        group: root
        mode: 0644

    - name: set logstash pattern file
      template:
        src: logstash_pattern
        dest: /opt/logstash/patterns
        owner: root
        group: root
        mode: 0644
      notify: restart logstash

    - name: set logstash init script
      template:
        src: logstash_init_script
        dest: /etc/init.d/logstash
        owner: root
        group: root
        mode: 0744
      notify: restart logstash

    - name: install kibana
      yum:
        name: kibana
        state: present

    - name: set kibana conf
      template:
        src: kibana_conf.yml
        dest: /etc/kibana/kibana.yml
        owner: root
        group: root
        mode: 0644
      notify: restart kibana

  handlers:
    - name: restart elasticsearch
      service:
        name: elasticsearch
        state: restarted

    - name: restart logstash
      service:
        name: logstash
        state: restarted

    - name: restart kibana
      service:
        name: kibana
        state: restarted
